<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="6" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-04-30T13:04:21Z" name="Suite" finished-at="2020-04-30T13:04:23Z" duration-ms="2293">
    <groups>
    </groups>
    <test started-at="2020-04-30T13:04:21Z" name="Create Customer API test" finished-at="2020-04-30T13:04:22Z" duration-ms="1860">
      <class name="com.amit.APITestingFramework.testcases.CreateCustommerTest">
        <test-method signature="validateCreateCustomerAPIWithInValidSecretKey(java.util.Hashtable)[pri:0, instance:com.amit.APITestingFramework.testcases.CreateCustommerTest@72cf2de5]" started-at="2020-04-30T13:04:21Z" name="validateCreateCustomerAPIWithInValidSecretKey" data-provider="data" finished-at="2020-04-30T13:04:22Z" duration-ms="1799" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=java@way2automation.com, name=Rahul Arora, description=Adding the Second customer in framework}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.amit.APITestingFramework.testcases.CreateCustommerTest.validateCreateCustomerAPIWithInValidSecretKey(CreateCustommerTest.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithInValidSecretKey -->
      </class> <!-- com.amit.APITestingFramework.testcases.CreateCustommerTest -->
    </test> <!-- Create Customer API test -->
    <test started-at="2020-04-30T13:04:21Z" name="Delete Customer API test" finished-at="2020-04-30T13:04:23Z" duration-ms="2293">
      <class name="com.amit.APITestingFramework.testcases.DeleteCustomerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.amit.APITestingFramework.testcases.DeleteCustomerTest@4678a2eb]" started-at="2020-04-30T13:04:20Z" name="setUp" finished-at="2020-04-30T13:04:21Z" duration-ms="315" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="deleteCustomer(java.util.Hashtable)[pri:0, instance:com.amit.APITestingFramework.testcases.DeleteCustomerTest@4678a2eb]" started-at="2020-04-30T13:04:21Z" name="deleteCustomer" data-provider="data" finished-at="2020-04-30T13:04:23Z" duration-ms="2239" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_HBwYnrY3y8VsnR}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method signature="deleteCustomer(java.util.Hashtable)[pri:0, instance:com.amit.APITestingFramework.testcases.DeleteCustomerTest@4678a2eb]" started-at="2020-04-30T13:04:21Z" name="deleteCustomer" data-provider="data" finished-at="2020-04-30T13:04:23Z" duration-ms="2237" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_HBwYBkSLCcFY2I}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method signature="deleteCustomer(java.util.Hashtable)[pri:0, instance:com.amit.APITestingFramework.testcases.DeleteCustomerTest@4678a2eb]" started-at="2020-04-30T13:04:21Z" name="deleteCustomer" data-provider="data" finished-at="2020-04-30T13:04:23Z" duration-ms="2241" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_HBwYmSYhsRxGJ0}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method signature="deleteCustomer(java.util.Hashtable)[pri:0, instance:com.amit.APITestingFramework.testcases.DeleteCustomerTest@4678a2eb]" started-at="2020-04-30T13:04:21Z" name="deleteCustomer" data-provider="data" finished-at="2020-04-30T13:04:23Z" duration-ms="2237" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ID key is not present in the JSON response expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ID key is not present in the JSON response expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.amit.APITestingFramework.testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amit.APITestingFramework.testcases.DeleteCustomerTest@4678a2eb]" started-at="2020-04-30T13:04:23Z" name="tearDown" finished-at="2020-04-30T13:04:23Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.amit.APITestingFramework.testcases.DeleteCustomerTest -->
    </test> <!-- Delete Customer API test -->
  </suite> <!-- Suite -->
</testng-results>
